name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # Run at midnight on each Saturday
    - cron:  '0 0 * * 6'
  workflow_dispatch:
    workflow: "*"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
      with:
        python-version: '3.12'

    - name: Install dependencies from PyPI
      run: |
        # We're doing an isolated wheel build below, so only install the
        # minimal dependencies needed to build a wheel and run the tests.
        python -m pip install build pytest

    - name: Install Suitesparse and SWIG
      run: |
        sudo apt install libsuitesparse-dev swig

    - name: Build a wheel
      run: |
        python -m build  # builds sdist, and then wheel from sdist
        ls dist/scikit*.whl # print it out for us to see
        pip install dist/scikit*.whl

    - uses: actions/upload-artifact@v4
      with:
        name: build.whl
        path: dist/scikit_umfpack-0.4.1-cp312-cp312-linux_x86_64.whl

    - name: Run test suite
      run: |
        cd docs
        pytest --pyargs scikits.umfpack
